### ISSUE TITLE
Persist window size/location

### ISSUE THREAD

**Issue by frostius** [CobaltFusion/DebugViewPP#370]
DebugView++ v1.8.0.103
Win 10 18363
Monitors: single 4K monitor

App window size/location is not persisting reliably.
See attached gif containing app version and example of non-persistence

![persist](https://user-images.githubusercontent.com/3818866/116823144-d5f0e600-ab50-11eb-9006-a8d80e5945d4.gif)

**Comment by janwilmans** [comment]
I can see it now also, it seems to happen when you put it _exactly_ on the limit at the edge of the screen.

**Comment by janwilmans** [comment]
I think the problem occurs because I take the coordinates of the window from[ 'GetWindowPlacement' ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowplacement) and compare them to coordinates from ['GetSystemMetrics'](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics) and looking at the coordinates I get, they aren't working in the same coordinate-system.

**Comment by frostius** [comment]
If I remember right, all the coordinates need to be in the same scale (DPI) as the primary monitor.  [GetScaleFactorForMonitor](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor) is what I use to convert dimensions

**Comment by frostius** [comment]
I just checked my code to see why I'm not seeing any similar issues.  I 
use GetWindowPlacement and SetWindowPlacement w/o any coordinate 
translation and it appears to work fine even with multiple monitors at 
different DPIs.  I do some additional checking to make sure the 
restoration is within valid bounds, but nothing DPI or scale related.

------ Original Message ------

**Comment by janwilmans** [comment]
All coordinates are in pixels so no scaling is involved, but I use 'GetSystemMetrics' to know whether the stored coordinates are actually visible right now.

for example, if you have two monitors the 'virtual screen' size might be (-1920,0) - (1920,1200), but if one monitor is disconnected, half of the virtual screen's coordinates is now an 'off screen' location. 

I have had complains in the past of 'debugview not showing', and this was the cause. So the prevent that I check the 'visibility' of the coordinates before restoring the window's position.

It not appears that the coordinates returned by GetSystemMetrics are not exactly aligned with the numbers coming from GetWindowPlacement... 

This is where the positions are stored:
https://github.com/CobaltFusion/DebugViewPP/blob/master/DebugView%2B%2B/MainFrame.cpp#L760

and here we read/check/set  them:
https://github.com/CobaltFusion/DebugViewPP/blob/master/DebugView%2B%2B/MainFrame.cpp#L684

**Comment by vadz** [comment]
FWIW the code linked above is wrong because `GetWindowPlacement()` takes the DPI into account and returns results adjusted for it, i.e. divided by 2 at 200% scaling, but `GetSystemMetrics()` does not (there is `GetSystemMetricsForDpi()` which does).

I should be able to make a PR to fix this, if this project still accepts them?

**Comment by janwilmans** [comment]
sure, I would love a PR, the project files may be a little out of date, let me know if you need me to update them first
