### ISSUE TITLE
I need DebugView++ to trap ::OutputDebugString() while the Visual Studio Debugger is also running

### ISSUE THREAD

**Issue by MadangLightHouse** [CobaltFusion/DebugViewPP#373]
Hi,

I need DebugView++ to trap ::OutputDebugString() while the Visual Studio Debugger is also running. As an alternative, is it possible to send it a windows message to display the formatted output string in the DebugView++ application window?

I tried downloading the source and building the solution on my machine (Windows 10, Visual Studio 2019 Professional) but the build failed. How do I build the solution? 

Cheers,

M

**Comment by janwilmans** [comment]
I have not found a way to hook into OutputDebugString() on windows 10, like it was possible on windows XP.
So that means debugviewpp cannot currently prevent Visual Studio from 'stealing' its messages.

You can use this SendMessage trick to send message to debugview++ directly.
https://github.com/CobaltFusion/DebugViewPP/blob/master/DbgMsgSrc/DbgMsgSrc.cpp#L231

About building, there are known issues with 'newer' vs2019 version.
maybe this applies to your situation https://github.com/CobaltFusion/DebugViewPP#vs2019

**Comment by MadangLightHouse** [comment]
Thank you so much Jan. I will have a look at your suggestions tomorrow and over the weekend.

Cheers,

Tony

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by janwilmans** [comment]
There is now also a vs2022 companion [extension ](https://marketplace.visualstudio.com/items?itemName=JanWilmans.OutputForwarder2022) available.
