### ISSUE TITLE
Support of Unicode OutputDebugStringW() 

### ISSUE THREAD

**Issue by RvanValen** [CobaltFusion/DebugViewPP#378]
I see that DebugView++ does not show Unicode output as this moment when using OutputDebugStringW().
According to MS there is a configuration call required to handle this (WaitForDebugEventEx())
https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw

Will this be added to future versions of DebugView++?

**Comment by janwilmans** [comment]
Debugview++ does not support this new behaviour and there are no plans to
support it.
The reason is that all strings in Debugview++ are std::strings' that do not
specify a specific encoding.

There is however a way to make it display UTF-8 encoded strings correctly
by enabling this windows feature:

I've tested this with chinese UTF-8 strings and it worked well, see
screenshots below.

I hope this can help.

Greetings,

Jan



[image: image.png]

[image: image.png]

**Comment by RvanValen** [comment]
Thank you for your quick response.
Good to know.

Unfortunately the github ticket does not show me the images - it shows [image: image.png] instead.
But I'll give UTF-8 a try. 

The issue can be closed, 

Best regards,
Roger.

**Comment by janwilmans** [comment]
![image](https://user-images.githubusercontent.com/5933444/178105607-f421e678-6b6c-4164-8e78-38941f153e25.png)

**Comment by janwilmans** [comment]
![image](https://user-images.githubusercontent.com/5933444/178105621-84825873-011e-4371-8302-bf817025f6cd.png)
![image](https://user-images.githubusercontent.com/5933444/178105626-173ca8c9-c1fe-4099-83b3-138f2c41eef9.png)
![image](https://user-images.githubusercontent.com/5933444/178105630-21224e3f-1f4e-4f0a-9d88-4c6a06b8942f.png)

**Comment by RvanValen** [comment]
Thanks!
